### ISSUE TITLE
New ScopeFoundry has broken 

### ISSUE THREAD

**Issue by rohandhall** [ercius/TemDataBrowser#5]
Scopefoundry update 2 months ago created some issues-- error says "ModuleNotFoundError: No module named 'ScopeFoundry.data_browser.viewers.file_info'"

**Comment by ercius** [comment]
Thanks for letting me know!

Look like ScopeFoundry reverted a fix from a few months back. I think the issue is that there is a package called `ScopeFoundry.data_browser` (with an `__init__` and a file in that package with the same name (`data_browser.py`). 

I raised an issue with ScopeFoundry and we will see how they want to deal with it. 
https://github.com/ScopeFoundry/ScopeFoundry/issues/47

**Comment by ercius** [comment]
This is now fixed in ScopeFoundry 1.4.2. TemDataBrowser will require this and later versions.
